### ISSUE TITLE
How to generate the libri100.json?

### ISSUE THREAD

**Issue by ArthurChien** [roman-vygon/triplet_loss_kws#1]
Hi~
I follow your README.md
But I didn't find anywhere to get libri100_train.json, libri100_dev.json, libri100_test.json
to convert LibriWords manifests with convert_path_prefix.ipynb

**Comment by roman-vygon** [comment]
> Hi~
> I follow your README.md
> But I didn't find anywhere to get libri100_train.json, libri100_dev.json, libri100_test.json
> to convert LibriWords manifests with convert_path_prefix.ipynb

Hello! Thank you for pointing it out, use [this updated link](https://drive.google.com/drive/folders/16jcbL3yPvFfZphL2VFg2mDcruh5KDXP2) for data manifests.

**Comment by ArthurChien** [comment]
Thank you

**Comment by Wonder1905** [comment]
Hi, I can't access or request access to files

**Comment by qzhsdu** [comment]
Dear author, this google link seems invalid, can you just reshare the files? Thanks a lot!
