### ISSUE TITLE
Memory Issues 

### ISSUE THREAD

**Issue by RHimaJyothi** [roman-vygon/triplet_loss_kws#4]
Hello Author,
        I'm trying to train the TripletEncoder.py but GPU throws CUDA out of memory error. Can you specify the memory requirements to train this code?

**Comment by tshadley** [comment]
Not the author but here's a quick observation:

`python TripletEncoder.py --name=test_encoder --manifest=35 --model=Res15 --per_class 5`

takes about 10GB:

|   0  TITAN X (Pascal)    On   | 00000000:04:00.0 Off |                  N/A |
| 63%   86C    P2   185W / 250W |  10005MiB / 12196MiB |     78%      Default |

So presumably the default

`python TripletEncoder.py --name=test_encoder --manifest=35 --model=Res15 --per_class 10`

would take 20GB

**Comment by RHimaJyothi** [comment]
Hi @tshadley 
          Can you able to reproduce the model with same size? I saw that there is mismatch in the model size, which is mentioned in the paper with the model shared with us.

**Comment by roman-vygon** [comment]
Hi everyone, sorry for the waiting, I've updated README with training specs for Res15 and Res8.
@RHimaJyothi, can you elaborate what you mean by the mismatch in model size?
